name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install django==3
        pip install graphene-django
    - name: Deploy to Pypi
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        pip install twine
        python setup.py sdist
        twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*